services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - establishment
      - iam

  establishment:
    build: ../establishment
    ports:
      - "8081:8080"

  iam:
    build: ../iam
    ports:
      - "8082:8080"